# Generated by Django 6.1.2 on 2026-10-07 15:42

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('tipo', models.CharField(choices=[('FUNCIONARIO', 'Funcionário'), ('RH', 'Gestor / RH')], default='FUNCIONARIO', max_length=20)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('jornada_semanal', models.IntegerField(default=40, help_text='Carga horária semanal em horas (ex: 40 ou 44)')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PontoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('entrada_1', models.TimeField(blank=True, null=True, verbose_name='Entrada 1')),
                ('saida_1', models.TimeField(blank=True, null=True, verbose_name='Saída Almoço')),
                ('entrada_2', models.TimeField(blank=True, null=True, verbose_name='Retorno Almoço')),
                ('saida_2', models.TimeField(blank=True, null=True, verbose_name='Saída 2')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ponto Diário',
                'verbose_name_plural': 'Pontos Diários',
                'unique_together': {('usuario', 'data')},
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoAjuste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referencia', models.DateField(verbose_name='Data do Ponto')),
                ('campo_alterado', models.CharField(choices=[('entrada_1', 'Entrada 1'), ('saida_1', 'Saída Almoço'), ('entrada_2', 'Retorno Almoço'), ('saida_2', 'Saída 2')], max_length=20)),
                ('novo_horario', models.TimeField(verbose_name='Novo Horário')),
                ('justificativa', models.TextField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado')], default='PENDENTE', max_length=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ponto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ajustes', to='core.pontodiario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
